# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/nestlabs/gateway/v2.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
try:
    from google.protobuf import runtime_version as _runtime_version
except ImportError:  # pragma: no cover - fallback for older protobuf
    class _RuntimeVersionStub:
        @staticmethod
        def ValidateProtobufRuntimeVersion(*args, **kwargs):
            return None
    _runtime_version = _RuntimeVersionStub()
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'proto/nestlabs/gateway/v2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.nest import rpc_pb2 as proto_dot_nest_dot_rpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/nestlabs/gateway/v2.proto\x12\x13nestlabs.gateway.v2\x1a\x14proto/nest/rpc.proto\"i\n\x0eObserveRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\tsubscribe\x18\x02 \x01(\x08\x12\x33\n\x06\x66ilter\x18\x03 \x03(\x0b\x32#.nestlabs.gateway.v2.ResourceFilter\"9\n\x0eResourceFilter\x12\x12\n\ntrait_type\x18\x01 \x01(\t\x12\x13\n\x0bresource_id\x18\x02 \x01(\t2X\n\x0eGatewayService\x12\x46\n\x07Observe\x12#.nestlabs.gateway.v2.ObserveRequest\x1a\x14.nest.rpc.StreamBody0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.nestlabs.gateway.v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVEREQUEST']._serialized_start=78
  _globals['_OBSERVEREQUEST']._serialized_end=183
  _globals['_RESOURCEFILTER']._serialized_start=185
  _globals['_RESOURCEFILTER']._serialized_end=242
  _globals['_GATEWAYSERVICE']._serialized_start=244
  _globals['_GATEWAYSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
