# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/weave/trait/description.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'proto/weave/trait/description.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/weave/trait/description.proto\x12\x17weave.trait.description\"\xbe\x01\n\x13\x44\x65viceIdentityTrait\x12>\n\x0cmanufacturer\x18\x02 \x01(\x0b\x32(.weave.trait.description.String_Indirect\x12<\n\nmodel_name\x18\x04 \x01(\x0b\x32(.weave.trait.description.String_Indirect\x12\x15\n\rserial_number\x18\x06 \x01(\t\x12\x12\n\nfw_version\x18\x07 \x01(\t\" \n\x0fString_Indirect\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0e\x46loat_Indirect\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1f\n\x0eInt32_Indirect\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.weave.trait.description_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEIDENTITYTRAIT']._serialized_start=65
  _globals['_DEVICEIDENTITYTRAIT']._serialized_end=255
  _globals['_STRING_INDIRECT']._serialized_start=257
  _globals['_STRING_INDIRECT']._serialized_end=289
  _globals['_FLOAT_INDIRECT']._serialized_start=291
  _globals['_FLOAT_INDIRECT']._serialized_end=322
  _globals['_INT32_INDIRECT']._serialized_start=324
  _globals['_INT32_INDIRECT']._serialized_end=355
# @@protoc_insertion_point(module_scope)
