# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/weave/trait/peerdevices.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
try:
    from google.protobuf import runtime_version as _runtime_version
except ImportError:  # pragma: no cover
    class _RuntimeVersionStub:
        @staticmethod
        def ValidateProtobufRuntimeVersion(*args, **kwargs):
            return None
        class Domain:
            PUBLIC = None
    _runtime_version = _RuntimeVersionStub()
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'proto/weave/trait/peerdevices.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/weave/trait/peerdevices.proto\x12\x17weave.trait.peerdevices\"\xde\x02\n\x10PeerDevicesTrait\x12\x45\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x34.weave.trait.peerdevices.PeerDevicesTrait.PeerDevice\x1a\x82\x02\n\nPeerDevice\x12Q\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x43.weave.trait.peerdevices.PeerDevicesTrait.PeerDevice.PeerDeviceInfo\x1a\xa0\x01\n\x0ePeerDeviceInfo\x12;\n\tdevice_id\x18\x01 \x01(\x0b\x32(.weave.trait.peerdevices.String_Indirect\x12=\n\x0b\x64\x65vice_type\x18\x02 \x01(\x0b\x32(.weave.trait.peerdevices.String_Indirect\x12\x12\n\nfw_version\x18\x05 \x01(\t\" \n\x0fString_Indirect\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0e\x46loat_Indirect\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1f\n\x0eInt32_Indirect\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.weave.trait.peerdevices_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEERDEVICESTRAIT']._serialized_start=65
  _globals['_PEERDEVICESTRAIT']._serialized_end=415
  _globals['_PEERDEVICESTRAIT_PEERDEVICE']._serialized_start=157
  _globals['_PEERDEVICESTRAIT_PEERDEVICE']._serialized_end=415
  _globals['_PEERDEVICESTRAIT_PEERDEVICE_PEERDEVICEINFO']._serialized_start=255
  _globals['_PEERDEVICESTRAIT_PEERDEVICE_PEERDEVICEINFO']._serialized_end=415
  _globals['_STRING_INDIRECT']._serialized_start=417
  _globals['_STRING_INDIRECT']._serialized_end=449
  _globals['_FLOAT_INDIRECT']._serialized_start=451
  _globals['_FLOAT_INDIRECT']._serialized_end=482
  _globals['_INT32_INDIRECT']._serialized_start=484
  _globals['_INT32_INDIRECT']._serialized_end=515
# @@protoc_insertion_point(module_scope)
