# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/nest/messages.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
try:
    from google.protobuf import runtime_version as _runtime_version
except ImportError:  # pragma: no cover
    class _RuntimeVersionStub:
        @staticmethod
        def ValidateProtobufRuntimeVersion(*args, **kwargs):
            return None
        class Domain:
            PUBLIC = None
    _runtime_version = _RuntimeVersionStub()
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'proto/nest/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/nest/messages.proto\x12\rnest.messages\"A\n\rSchemaVersion\x12\x16\n\x0e\x63urrentVersion\x18\x01 \x01(\r\x12\x18\n\x10minCompatVersion\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.nest.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEMAVERSION']._serialized_start=44
  _globals['_SCHEMAVERSION']._serialized_end=109
# @@protoc_insertion_point(module_scope)
