# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/nest/rpc.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'proto/nest/rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from proto.nest import iface_pb2 as proto_dot_nest_dot_iface__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/nest/rpc.proto\x12\x08nest.rpc\x1a\x19google/protobuf/any.proto\x1a\x16proto/nest/iface.proto\"5\n\x0cObjectIdPair\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\">\n\x14\x44ynamicProp_Indirect\x12&\n\x08property\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"\x93\x01\n\x10TraitGetProperty\x12&\n\x06object\x18\x01 \x01(\x0b\x32\x16.nest.rpc.ObjectIdPair\x12\x11\n\tsomething\x18\x02 \x01(\x0c\x12,\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x1e.nest.rpc.DynamicProp_Indirect\x12\x16\n\x0esomething_else\x18\x04 \x01(\x03\"@\n\x14PropertyKeyTraitPair\x12\x14\n\x0cproperty_key\x18\x01 \x01(\t\x12\x12\n\ntrait_type\x18\x02 \x01(\t\"\x9e\x01\n\x10TraitSetProperty\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x34\n\x0cproperty_key\x18\x04 \x01(\x0b\x32\x1e.nest.rpc.PropertyKeyTraitPair\x12(\n\tinterface\x18\x07 \x01(\x0b\x32\x15.nest.iface.Interface\")\n\x08SomeList\x12\r\n\x05\x66irst\x18\x01 \x01(\t\x12\x0e\n\x06second\x18\x02 \x01(\t\"\x86\x01\n\x0bNestMessage\x12\'\n\x03set\x18\x01 \x03(\x0b\x32\x1a.nest.rpc.TraitSetProperty\x12\'\n\x03get\x18\x03 \x03(\x0b\x32\x1a.nest.rpc.TraitGetProperty\x12%\n\tsome_list\x18\x05 \x01(\x0b\x32\x12.nest.rpc.SomeList\"N\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\"d\n\nStreamBody\x12&\n\x07message\x18\x01 \x03(\x0b\x32\x15.nest.rpc.NestMessage\x12 \n\x06status\x18\x02 \x01(\x0b\x32\x10.nest.rpc.Status\x12\x0c\n\x04noop\x18\x0f \x03(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.nest.rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECTIDPAIR']._serialized_start=85
  _globals['_OBJECTIDPAIR']._serialized_end=138
  _globals['_DYNAMICPROP_INDIRECT']._serialized_start=140
  _globals['_DYNAMICPROP_INDIRECT']._serialized_end=202
  _globals['_TRAITGETPROPERTY']._serialized_start=205
  _globals['_TRAITGETPROPERTY']._serialized_end=352
  _globals['_PROPERTYKEYTRAITPAIR']._serialized_start=354
  _globals['_PROPERTYKEYTRAITPAIR']._serialized_end=418
  _globals['_TRAITSETPROPERTY']._serialized_start=421
  _globals['_TRAITSETPROPERTY']._serialized_end=579
  _globals['_SOMELIST']._serialized_start=581
  _globals['_SOMELIST']._serialized_end=622
  _globals['_NESTMESSAGE']._serialized_start=625
  _globals['_NESTMESSAGE']._serialized_end=759
  _globals['_STATUS']._serialized_start=761
  _globals['_STATUS']._serialized_end=839
  _globals['_STREAMBODY']._serialized_start=841
  _globals['_STREAMBODY']._serialized_end=941
# @@protoc_insertion_point(module_scope)
