# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nest/trait/structure.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'nest/trait/structure.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anest/trait/structure.proto\x12\x14nest.trait.structure\x1a\x19google/protobuf/any.proto\"t\n\x12StructureInfoTrait\x12\x11\n\tlegacy_id\x18\x01 \x01(\t\x12\x0c\n\x04ssid\x18\n \x01(\t\x12=\n\x0fresource_status\x18\r \x03(\x0b\x32$.nest.trait.structure.ResourceStatus\"7\n\x0eResourceStatus\x12\x15\n\rresource_type\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\" \n\x0fString_Indirect\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0e\x46loat_Indirect\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1f\n\x0eInt32_Indirect\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nest.trait.structure_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRUCTUREINFOTRAIT']._serialized_start=79
  _globals['_STRUCTUREINFOTRAIT']._serialized_end=195
  _globals['_RESOURCESTATUS']._serialized_start=197
  _globals['_RESOURCESTATUS']._serialized_end=252
  _globals['_STRING_INDIRECT']._serialized_start=254
  _globals['_STRING_INDIRECT']._serialized_end=286
  _globals['_FLOAT_INDIRECT']._serialized_start=288
  _globals['_FLOAT_INDIRECT']._serialized_end=319
  _globals['_INT32_INDIRECT']._serialized_start=321
  _globals['_INT32_INDIRECT']._serialized_end=352
# @@protoc_insertion_point(module_scope)
