# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/nest/trait/user.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
try:
    from google.protobuf import runtime_version as _runtime_version
except ImportError:  # pragma: no cover
    class _RuntimeVersionStub:
        @staticmethod
        def ValidateProtobufRuntimeVersion(*args, **kwargs):
            return None
        class Domain:
            PUBLIC = None
    _runtime_version = _RuntimeVersionStub()
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'proto/nest/trait/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/nest/trait/user.proto\x12\x0fnest.trait.user\"3\n\rUserInfoTrait\x12\x11\n\tlegacy_id\x18\x01 \x01(\t\x12\x0f\n\x07unknown\x18\x02 \x01(\x05\" \n\x0fString_Indirect\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x0e\x46loat_Indirect\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1f\n\x0eInt32_Indirect\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.nest.trait.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINFOTRAIT']._serialized_start=48
  _globals['_USERINFOTRAIT']._serialized_end=99
  _globals['_STRING_INDIRECT']._serialized_start=101
  _globals['_STRING_INDIRECT']._serialized_end=133
  _globals['_FLOAT_INDIRECT']._serialized_start=135
  _globals['_FLOAT_INDIRECT']._serialized_end=166
  _globals['_INT32_INDIRECT']._serialized_start=168
  _globals['_INT32_INDIRECT']._serialized_end=199
# @@protoc_insertion_point(module_scope)
